// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAx3f_Oe6lwCSaPIPCClWYzbFtWADLb58A',
    appId: '1:387669316257:android:911f9d7bc0d54241fb16e0',
    messagingSenderId: '387669316257',
    projectId: 'hogarfix-cec7b',
    storageBucket: 'hogarfix-cec7b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGs8m5NrdBJDO2E8C9eBkzXGV1eLrWMbI',
    appId: '1:387669316257:ios:5bf45fe28e53b2bffb16e0',
    messagingSenderId: '387669316257',
    projectId: 'hogarfix-cec7b',
    storageBucket: 'hogarfix-cec7b.appspot.com',
    iosBundleId: 'com.example.flutterFront',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGs8m5NrdBJDO2E8C9eBkzXGV1eLrWMbI',
    appId: '1:387669316257:ios:5bf45fe28e53b2bffb16e0',
    messagingSenderId: '387669316257',
    projectId: 'hogarfix-cec7b',
    storageBucket: 'hogarfix-cec7b.appspot.com',
    iosBundleId: 'com.example.flutterFront',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCs1eSdlehTgqXP-RQIcQqTuH8_Q8GMLg4',
    appId: '1:387669316257:web:92121c946f15f4d5fb16e0',
    messagingSenderId: '387669316257',
    projectId: 'hogarfix-cec7b',
    authDomain: 'hogarfix-cec7b.firebaseapp.com',
    storageBucket: 'hogarfix-cec7b.appspot.com',
    measurementId: 'G-Q2TMVT4CTT',
  );
}
